tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/services"
tap "sass/sass"
tap "siderolabs/tap"
brew "xz"
brew "glib"
brew "harfbuzz"
brew "zstd"
brew "libtiff"
brew "openjdk"
brew "ant"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "autopep8"
brew "bat"
brew "cmake"
brew "cppcheck"
brew "curl"
brew "fastfetch"
brew "fd"
brew "unbound"
brew "gnutls"
brew "openjpeg"
brew "leptonica"
brew "libass"
brew "pango"
brew "tesseract"
brew "ffmpeg"
brew "gcc"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "gnuplot"
brew "go"
brew "golang-migrate"
brew "hdf5"
brew "helm"
brew "helmfile"
brew "libheif"
brew "libraw"
brew "jdtls"
brew "jq"
brew "k9s"
brew "llvm"
brew "mas"
brew "protobuf"
brew "mysql@8.4"
brew "tree-sitter"
brew "neovim"
brew "openblas"
brew "openjdk@17"
brew "openssh"
brew "pandoc"
brew "pngpaste"
brew "ripgrep"
brew "rustup"
brew "sqlc"
brew "stow"
brew "stripe-cli"
brew "swift-format"
brew "tailwindcss"
brew "tailwindcss-language-server"
brew "texlab"
brew "thefuck"
brew "tlrc"
brew "tree"
brew "uncrustify"
brew "vips"
brew "watch"
brew "watchman"
brew "zoxide"
brew "sass/sass/sass"
brew "siderolabs/tap/talosctl"
cask "balenaetcher"
cask "basictex"
cask "chatgpt"
cask "dbeaver-community"
cask "discord"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "logi-options+"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "mongodb-compass"
cask "multiviewer-for-f1"
cask "nordvpn"
cask "notion"
cask "obsidian"
cask "postman"
cask "qflipper"
cask "raspberry-pi-imager"
cask "rotato"
cask "sf-symbols"
cask "skim"
cask "slack"
cask "spotify"
cask "trezor-suite"
cask "wwdc"
cask "zoom"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Balatro+", id: 6502451661
mas "Boop", id: 1518425043
mas "Bridge Constructor+", id: 1587908263
mas "Compressor", id: 424390742
mas "CustomSymbols", id: 1566662030
mas "Developer", id: 640199958
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "Goodnotes", id: 1444383602
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Logic Pro", id: 634148309
mas "Mini Motorways", id: 1456188526
mas "Motion", id: 434290957
mas "Numbers", id: 409203825
mas "Outlanders 2", id: 1614682164
mas "Pages", id: 409201541
mas "Timery", id: 1425368544
mas "WHAT THE CAR?", id: 1534708672
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835
