require('which-key').add {
    { "<leader>d",   group = "[D]iagnostics" },
    { "<leader>d_",  hidden = true },
    { "<leader>e",   group = "[E]dit" },
    { "<leader>e_",  hidden = true },
    { "<leader>f",   group = "[F]ind" },
    { "<leader>f_",  hidden = true },
    { "<leader>fw",  group = "[F]ind in [W]orkspace" },
    { "<leader>fw_", hidden = true },
    { "<leader>g",   group = "[G]it" },
    { "<leader>g_",  hidden = true },
    { "<leader>gl",  group = "Git [L]og" },
    { "<leader>gl_", hidden = true },
    { "<leader>h",   group = "[H]arpoon" },
    { "<leader>h_",  hidden = true },
    { "<leader>p",   group = "[P]roject" },
    { "<leader>p_",  hidden = true },
    { "<leader>v",   group = "[V]iew" },
    { "<leader>v_",  hidden = true },
}
