If:
  PathMatch: .*\.cpp

CompileFlags:
  Add: [-std=c++20]

---

CompileFlags:                     # Tweak the parse settings
  Add: [-Wall, -isystem, -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1]


